<?xml version='1.0' encoding='UTF-8'?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>flatland_core</name>
  <version>2.0.0</version>
  <description>
    This is the metapackage for flatland (ROS 2).
  </description>
  <maintainer email="leventfaruksoysal6@gmail.com">Worthle</maintainer>
  <license>BSD-3-Clause</license>
  <url type="website">https://github.com/Worthle</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>flatland_msgs</exec_depend>
  <exec_depend>flatland_plugins</exec_depend>
  <exec_depend>flatland_server</exec_depend>
  <exec_depend>flatland_viz</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
