<?xml version="1.0"?>
<package format="3">
  <name>flatland</name>
  <version>2.0.0</version>
  <description>Flatland 2 ROS 2 Humble bringup, robot models and warehouse assets.</description>
  <maintainer email="leventfaruksoysal6@gmail.com">Worthle</maintainer>
  <license>BSD-3-Clause</license>
  <url type="website">https://github.com/Worthle</url>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>flatland_core</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>ackermann_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
